---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source: embed
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
library(plotly)
library(flexdashboard)
library(rvest)
library(httr)
```

```{r}
api_url = "https://data.cityofnewyork.us/resource/43nn-pn8j.csv"

rest_inspections = 
  GET(api_url, query = list("$limit" = 50000)) %>% 
  content("parsed")

rest_inspections_df = 
  rest_inspections %>% 
  filter(grade %in% c("A", "B", "C"), boro != "0")
```


Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
plot_1 =
  rest_inspections_df %>%
  mutate(text_label = 
           str_c("Grade: ", grade, "\nCuisine: ", cuisine_description, "\nBoro ", boro)) %>% 
  plot_ly(
          x = ~longitude, y = ~latitude, color = ~grade,  text = ~text_label, 
          type = "scatter", mode = "markers", colors = "viridis", alpha = 0.3)

layout(plot_1, xaxis = list(range = c(-73.65, -74.25)), yaxis = list(range = c(40.5, 40.93)))
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
plot_2 = 
  rest_inspections_df %>%
  group_by(boro) %>%
  count(grade) %>% 
  mutate(boro_grade = str_c("", boro, " ", grade)) %>%
  plot_ly(
    x = ~boro_grade, y = ~n, fillcolor = ~boro,
    type = "bar"
  )

layout(plot_2, xaxis = list(title = "Boro & Grade"), yaxis = list(title = "Number of Restaurants"))
```

### Chart C

```{r}

```

